Repository StochSS/GillesPy2, pull requests merged in 2021-06, with the labels that each got.

#520 Build step refactor
  gillespy2/__init__.py
  gillespy2/core/model.py
  gillespy2/solvers/cpp/__init__.py
  gillespy2/solvers/cpp/build/__init__.py
  gillespy2/solvers/cpp/build/build_engine.py
  gillespy2/solvers/cpp/build/make.py
  gillespy2/solvers/cpp/build/template_gen.py
  gillespy2/solvers/cpp/c_base/Makefile
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESimulation.cpp
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESolver.cpp
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESolver.h
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODETemplate.cpp
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/VariableODETemplate.cpp
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/makefile
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASimulation.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASolver.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASolver.h
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SimulationTemplate.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/VariableSimulationTemplate.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/makefile
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSimulation.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSolver.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSolver.h
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauSimulationTemplate.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/VariableTauSimulationTemplate.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/makefile
  gillespy2/solvers/cpp/c_base/template/template.cpp
  gillespy2/solvers/cpp/c_base/template/template.h
  gillespy2/solvers/cpp/c_base/template/template_defaults.h
  gillespy2/solvers/cpp/c_base/template/template_definitions.h
  gillespy2/solvers/cpp/c_decoder.py
  gillespy2/solvers/cpp/c_solver.py
  gillespy2/solvers/cpp/ode_c_solver.py
  gillespy2/solvers/cpp/ssa_c_solver.py
  gillespy2/solvers/cpp/tau_leaping_c_solver.py
  gillespy2/solvers/utilities/cpp_support_test.py
  gillespy2/solvers/utilities/solverutils.py
  test/run_tests.py
  test/test_build_engine.py
  test/test_c_solvers.py
  test/test_check_cpp_support.py
  test/test_variable_solvers.py
Labels: enhancement

#524 Update workflow payload to include `ref` field
  .github/workflows/biosim-release.yml
Labels: bug, fixed

#523 C++ and Python Solver Profiling
  test/profiling/Makefile
  test/profiling/__init__.py
  test/profiling/c_profiler.py
  test/profiling/performance_data.py
  test/profiling/python_profiler.py
  test/test_c_solver_perf.py
  test/test_python_solver_perf.py
Labels: enhancement

#531 Fix: precompile regression
  gillespy2/solvers/cpp/build/build_engine.py
  gillespy2/solvers/cpp/c_solver.py
  test/test_c_solvers.py
Labels: bug, fixed

#535 Migration from TravisCI to Github Actions for Testing
  .github/workflows/run-tests.yml
Labels: enhancement

#525 C++ Solver Cleanup
  gillespy2/solvers/cpp/c_base/Makefile
  gillespy2/solvers/cpp/c_base/model.cpp
  gillespy2/solvers/cpp/c_base/model.h
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESimulation.cpp
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESolver.cpp
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESolver.h
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASimulation.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASolver.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASolver.h
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSimulation.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSolver.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSolver.h
  gillespy2/solvers/cpp/c_base/template/template.cpp
  gillespy2/solvers/cpp/c_base/template/template.h
Labels: enhancement

#482 Model to json
  gillespy2/core/assignmentrule.py
  gillespy2/core/events.py
  gillespy2/core/functiondefinition.py
  gillespy2/core/jsonify.py
  gillespy2/core/model.py
  gillespy2/core/parameter.py
  gillespy2/core/raterule.py
  gillespy2/core/reaction.py
  gillespy2/core/results.py
  gillespy2/core/species.py
  test/run_tests.py
  test/test_jsonify.py
Labels: enhancement

#538 Hotfix: C++ Tau Leaping Solver RNG reinstantiation without seed
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSolver.cpp
Labels: bug

#530 Arg parser
  gillespy2/solvers/cpp/c_base/Makefile
  gillespy2/solvers/cpp/c_base/arg_parser.cpp
  gillespy2/solvers/cpp/c_base/arg_parser.h
  gillespy2/solvers/cpp/c_base/ode_cpp_solver/ODESimulation.cpp
  gillespy2/solvers/cpp/c_base/ssa_cpp_solver/SSASimulation.cpp
  gillespy2/solvers/cpp/c_base/tau_leaping_cpp_solver/TauLeapingSimulation.cpp
  gillespy2/solvers/cpp/c_solver.py
  gillespy2/solvers/cpp/ode_c_solver.py
  gillespy2/solvers/cpp/ssa_c_solver.py
  gillespy2/solvers/cpp/tau_leaping_c_solver.py
Labels: enhancement

#541 Added PyPi publish Github action
  .github/workflows/pypi-publish.yml
Labels: enhancement

#543 Added action to run test suite on Python versions 3.6 - 3.9
  .github/workflows/run-full-tests.yml
Labels: enhancement

#544 Fixed major C++ and Numpy solver regression caused by species sanitization.
  gillespy2/core/model.py
Labels: bug

#549 Fix `Model#get_best_solver_algo`
  gillespy2/core/model.py
Labels: bug

#553 Set reaction rate as str
  gillespy2/core/reaction.py
Labels: enhancement

#554 Added RumseyReactor robust model to test suite.
  test/example_models.py
  test/test_model.py
Labels: enhancement

#559 Made small tweaks to documentation stylesheets to improve readability.
  docs/_static/css/gillespy2_alabaster_customizations.css
  docs/_static/fonts/FiraCode-Retina.ttf
  docs/_static/fonts/Roboto-Regular.ttf
Labels: enhancement

#561 Updated dead links in README.md.
  README.md
Labels: bug

#556 Updated and refactored the StartHere notebook.
  examples/StartHere.ipynb
Labels: enhancement

#555 Added check and tests to verify behavior of SBML reactions.
  gillespy2/sbml/SBMLimport.py
  test/assets/model_without_propensities.xml
  test/test_SBML.py
Labels: bug, fixed

#562 Fixed broken documentation generation.
  gillespy2/core/assignmentrule.py
  gillespy2/core/events.py
  gillespy2/core/functiondefinition.py
  gillespy2/core/gillespySolver.py
  gillespy2/core/jsonify.py
  gillespy2/core/model.py
  gillespy2/core/parameter.py
  gillespy2/core/reaction.py
  gillespy2/core/results.py
  gillespy2/core/species.py
  gillespy2/solvers/cpp/build/build_engine.py
  gillespy2/solvers/cpp/build/template_gen.py
  gillespy2/solvers/cpp/c_decoder.py
  gillespy2/solvers/cpp/c_solver.py
  gillespy2/solvers/cpp/ode_c_solver.py
  gillespy2/solvers/cpp/ssa_c_solver.py
  gillespy2/solvers/cpp/tau_leaping_c_solver.py
  gillespy2/solvers/numpy/ode_solver.py
  gillespy2/solvers/numpy/ssa_solver.py
  gillespy2/solvers/numpy/tau_hybrid_solver.py
  gillespy2/solvers/numpy/tau_leaping_solver.py
  gillespy2/solvers/utilities/solverutils.py
Labels: bug

#567 Updated legacy readthedocs.io links to new documentation domain.
  README.md
  examples/StartHere.ipynb
Labels: enhancement

#569 Fixed version number (we should really automate this)
  gillespy2/__version__.py
Labels: bug
