Repository StochSS/GillesPy2, pull requests merged in 2021-07, with the labels that each got.

#577 Generic function definitions
  gillespy2/core/functiondefinition.py
  gillespy2/sbml/SBMLexport.py
  gillespy2/solvers/numpy/tau_hybrid_solver.py
  gillespy2/stochss/StochSSexport.py
  test/example_models.py
  test/test_SBML.py
  test/test_model.py
Labels: bug, enhancement

#579 Updated docstrings in `basic_` solvers to contain deprecation notice.
  gillespy2/solvers/numpy/basic_ode_solver.py
  gillespy2/solvers/numpy/basic_tau_hybrid_solver.py
  gillespy2/solvers/numpy/basic_tau_leaping_solver.py
Labels: enhancement

#587 Fix segfault in C++ tau select function
  gillespy2/solvers/cpp/c_base/Tau/tau.cpp
Labels: bug
