Repository StochSS/GillesPy2, pull requests merged in 2022-12, with the labels that each got.

#888 Auto docs build
  .github/workflows/update-docs.yaml
  docs/Makefile
Labels: enhancement, Docs

#889 Update README.md
  README.md
Labels: bug

#890 Fixing packaging for SCons
  MANIFEST.in
  gillespy2/solvers/cpp/build/make.py
  test/test_build_engine.py
Labels: bug

#892 Incorrect Errors
  gillespy2/core/events.py
  gillespy2/core/functiondefinition.py
Labels: enhancement

#893 Pylintrc file
  .github/workflows/pylint_on_pull_request.yml
  .pylintrc
  gillespy2/core/__init__.py
  gillespy2/core/assignmentrule.py
  gillespy2/core/events.py
  gillespy2/core/functiondefinition.py
  gillespy2/core/gillespyError.py
  gillespy2/core/gillespySolver.py
  gillespy2/core/jsonify.py
  gillespy2/core/liveGraphing.py
  gillespy2/core/model.py
  gillespy2/core/raterule.py
  gillespy2/core/reaction.py
  gillespy2/core/results.py
  gillespy2/core/sortableobject.py
  gillespy2/core/species.py
  gillespy2/core/timespan.py
  gillespy2/sbml/SBMLexport.py
  gillespy2/sbml/SBMLimport.py
Labels: enhancement

#903 Tauhybridsolver tau selection bugs break opioid model
  gillespy2/solvers/utilities/Tau.py
  test/example_models.py
  test/test_hybrid_solver_opioid_model.py
Labels: bug

#900 Events assignment rounding for discrete/continuous species
  gillespy2/solvers/numpy/tau_hybrid_solver.py
  test/run_integration_tests.py
  test/test_hybrid_event_round.py
Labels: bug

#891 Fixes #874 for TauHybridSolver
  gillespy2/core/model.py
  gillespy2/solvers/cpp/c_base/tau_hybrid_cpp_solver/HybridModel.h
  gillespy2/solvers/cpp/c_base/tau_hybrid_cpp_solver/TauHybridSolver.cpp
  gillespy2/solvers/cpp/tau_hybrid_c_solver.py
  gillespy2/solvers/numpy/tau_hybrid_solver.py
  test/run_integration_tests.py
  test/test_c_decode.py
  test/test_hybrid_negative_state.py
  test/test_run_output.py
Labels: Cleanup
